nelmio_api_doc:
    documentation:
        info:
            title: Web Investissement
            description: API Web Investissement
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
