# Used in project
version: "3.8"

services:
  php-apache:
    container_name: www-net
    ports:
      - "80:80"
    build: ../docker/php
    volumes:
      - ../netinvestissement:/var/www/html
      - ../docker/php/vhosts.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - dev

  db:
    image: mysql
    container_name: db_net
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password1234
      - MYSQL_DATABASE=netdev
      - MYSQL_USER=netdev
      - MYSQL_PASSWORD=password1234
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-net
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:

